# Generated by Django 3.0.8 on 2020-08-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_tarefabd_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefabd',
            old_name='edited',
            new_name='editar',
        ),
    ]
