# Generated by Django 3.0.8 on 2020-08-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_auto_20200822_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefabd',
            old_name='editar',
            new_name='completado',
        ),
    ]
